### PR TITLE
[Update] Added Russian Translation

### PR DESCRIPTION
**Pull request by LeonusDH**

### CODE REVIEW

**Comment by emipa606** [comment]
Thanks, should be published in 98b208b

**Comment by MewnGoddess** [comment]
So LeonusDH took my translation from the Steam Workshop, changed only 2 words and two brackets lol, and provided it to you <_<
Anyway now the translation is included in the main mod, which is nice x) 

Btw, thanks for your awesome work, Mlie, you are a legend!

**Comment by LeonusDH** [comment]
> So LeonusDH took my translation from the Steam Workshop, changed only 2 words and two brackets lol, and provided it to you <_< Anyway now the translation is included in the main mod, which is nice x)
> 
> Btw, thanks for your awesome work, Mlie, you are a legend!

I used DeepL for the translation and edited it afterwards to make it look good.
If it looks like yours, nothing I can do about it.

**Comment by MewnGoddess** [comment]
> 
> I used DeepL for the translation and edited it afterwards to make it look good. If it looks like yours, nothing I can do about it.

You're making a fool out of yourself, good sir, because everything can be easily proven: my translation is dated October 27th 2022 (https://steamcommunity.com/sharedfiles/filedetails/?id=2880345853).
This is a side-by-side comparison of the two translations on the picrel. I used some words that were not it the original text and used game-specific ternary conditional operator (I believe DeepL wouldn't know of it X)). And you just copied everything and changed two words and two parentheses, and that's it.

**Pull request merged**
